---
- name: Install Hammerspoon
  community.general.homebrew_cask:
    name: hammerspoon
    state: present
- name: Copy Hammerspoon config
  ansible.builtin.template:
    src: init.lua.j2
    dest: "{{ config_dir }}/hammerspoon/init.lua"
    mode: "0644"
  notify: Reload Hammerspoon
- name: Set init.lua location
  community.general.osx_defaults:
    domain: org.hammerspoon.Hammerspoon
    key: MJConfigFile
    value: "{{ config_dir }}/hammerspoon/init.lua"
