---
shells_fisher_plugins:
  - tsfoster/posix-source
  - tsfoster/docker-tools
  - tsfoster/fish-elm-completion
  - fisherman/getopts
  - catppuccin/fish
  - jethrokuan/fzf
  - topdroplabs/docker-fish-completion
shells_path_entries_interactive:
  - bin
  - node_modules/.bin
shells_path_entries:
  - "{{ ansible_facts['env']['HOME'] }}/.asdf/shims"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/go/bin"
  - "{{ ansible_facts['env']['HOME'] }}/.local/bin"
  - "{{ ansible_facts['env']['HOME'] }}/.cargo/bin"
  - /usr/local/sbin
  - /usr/local/bin
shells_path_entries_darwin:
  - "{{ homebrew_prefix }}/bin"
  - "{{ homebrew_prefix }}/sbin"
  - "{{ homebrew_cask_appdir }}/opt/openjdk/bin"
  - /Applications/Setapp/Soulver.app/Contents/MacOS/CLI
shells_uv:
  xdg_data: "{{ ansible_facts['env']['HOME'] }}/.local/share"
  fd_default:
    --exclude node_modules --exclude .git --exclude elm-stuff --exclude bower_components --exclude target --exclude .DS_Store --exclude .sass-cache
    --hidden
  iCloud: "{{ ansible_facts['env']['HOME'] }}/Library/Mobile Documents/com~apple~CloudDocs"
  isMac: "{{ ansible_facts['system'] == 'Darwin' }}"
  editor: "zmx attach nvim-(random) nvim"
  shell_path_entries: "{{ shells_path_entries + (lookup('vars', 'shells_path_entries_' + (ansible_facts['system'] | lower)) | default([])) }}"
  shell_path_entries_interactive: "{{ shells_path_entries_interactive }}"
shells_variables_base:
  - name: PAGER
    value: nvim +PagerInit -
    export: true
  - name: XDG_CONFIG_HOME
    value: "{{ config_dir }}"
    export: true
  - name: XDG_DATA_HOME
    value: "{{ shells_uv.xdg_data }}"
    export: true
  - name: XDG_CACHE_HOME
    value: "{{ ansible_facts['env']['HOME'] }}/.local/cache"
    export: true
  - name: XDG_STATE_HOME
    value: "{{ ansible_facts['env']['HOME'] }}/.local/state"
    export: true
  - name: GOPATH
    value: "{{ shells_uv.xdg_data }}/go"
    export: true
  - name: HOMEBREW_CASK_OPTS
    value: "{{ shells_uv.isMac | ternary('--appdir=' + homebrew_cask_appdir, omit) }}"
    export: true
  - name: FD_DEFAULT_FLAGS
    value: "{{ shells_uv.fd_default }}"
    export: true
  - name: RIPGREP_CONFIG_PATH
    value: "{{ config_dir }}/ripgreprc"
    export: true
  - name: FZF_DEFAULT_COMMAND
    value: "fd --type file {{ shells_uv.fd_default }}"
    export: true
  - name: EDITOR
    value: "{{ shells_uv.editor }}"
    export: true
  - name: config
    export: true
    value: "{{ config_dir }}"
  - name: data
    export: true
    value: "{{ shells_uv.xdg_data }}"
  - name: workspace
    export: true
    value: "{{ ansible_facts['env']['HOME'] }}/workspace"
  - name: OS
    value: "{{ shells_uv.isMac | ternary('Mac', 'Other') }}"
  - name: iCloud
    export: true
    value: "{{ shells_uv.isMac | ternary(shells_uv.iCloud, omit) }}"
  - name: documents
    export: true
    value: "{{ shells_uv.isMac | ternary(shells_uv.iCloud + '/Documents', omit) }}"
  - name: work
    export: true
    value: "{{ shells_uv.isMac | ternary(shells_uv.iCloud + '/Documents/Work', omit) }}"
  - name: clients
    export: true
    value: "{{ shells_uv.isMac | ternary(shells_uv.iCloud + '/Documents/Work/Clients', omit) }}"
  - name: obsidian
    export: true
    value: "{{ shells_uv.isMac | ternary(ansible_facts['env']['HOME'] + '/Library/Mobile Documents/iCloud~md~obsidian/Documents/Vault', omit) }}"
shells_variables_darwin:
  - name: HOMEBREW_PREFIX
    value: "{{ homebrew_prefix }}"
    export: true
  - name: HOMEBREW_CELLAR
    value: "{{ homebrew_prefix }}/Cellar"
    export: true
  - name: HOMEBREW_REPOSITORY
    value: "{{ homebrew_prefix }}"
    export: true
  - name: MANPATH
    value_multiple:
      - "{{ homebrew_prefix }}/share/man"
    keep_existing: true
    export: true
    path: true
  - name: INFOPATH
    value_multiple:
      - "{{ homebrew_prefix }}/share/info"
    keep_existing: true
    export: true
    path: true
shells_variables: "{{ shells_variables_base + (lookup('vars', 'shells_variables_' + (ansible_facts['system'] | lower)) | default([])) }}"
shells_fish_universal_variables:
  - name: fish_user_paths
    value_multiple: "{{ shells_uv.shell_path_entries }}"
    export: true
    path: true
shells_abbreviations:
  - name: an
    value: ansible
  - name: ap
    value: ansible-playbook
  - name: d
    value: docker
  - name: dm
    value: docker-machine
  - name: dsw
    value: docker swarm
  - name: ds
    value: docker service
  - name: dc
    value: docker compose
  - name: g
    value: git
  - name: gca
    value: git commit --amend
  - name: gcane
    value: git commit --amend --no-edit
  - name: gd
    value: git diff
  - name: gdc
    value: git diff --cached
  - name: gst
    value: git stash
  - name: gsp
    value: git stash pop
  - name: gs
    value: git status
  - name: gh
    value: "{{ shells_op_plugin_run_prefix }} gh"
  - name: glab
    value: "{{ shells_op_plugin_run_prefix }} glab"
  - name: doctl
    value: "{{ shells_op_plugin_run_prefix }} doctl"
  - name: l
    value: ls
  - name: la
    value: ls -A
  - name: ll
    value: ls -l
  - name: psg
    value: psgrep
  - name: words
    value: "grep < /usr/share/dict/words"
  - name: lw
    value: "ls -l (which"
    shell_alias: false
  - name: v
    value: "{{ shells_uv.editor }}"
  - name: e
    value: "{{ shells_uv.editor }}"
    shell_alias: false
