---
- name: Configure localhost
  hosts: localhost
  roles:
    - role: shells
      tags: ["shells"]
    - role: dot_dirs
      tags: ["dot_dirs"]
    - role: ssh
      tags: ["ssh"]
    - role: npm
      tags: ["npm"]
    - role: homebrew
      tags: ["homebrew"]
      when: ansible_facts["system"] == "Darwin"
    - role: macos
      tags: ["macos"]
      when: ansible_facts["system"] == "Darwin"
    - role: nvim
      tags: ["nvim"]
    - role: hammerspoon
      tags: ["hammerspoon"]
      when: ansible_facts["system"] == "Darwin"
    - role: macos_navigation
      tags: ["macos_navigation"]
      when: ansible_facts["system"] == "Darwin"
    - role: fonts
      tags: ["fonts"]
      when: ansible_facts["system"] == "Darwin"
    - role: macos_dictionaries
      tags: ["dictionaries"]
      when: ansible_facts["system"] == "Darwin"
    - role: docker
      tags: ["docker"]
    - role: java
      tags: ["java"]
    - role: cli_tools
      tags: ["cli_tools"]
    - role: alfred
      tags: ["alfred"]
      when: ansible_facts["system"] == "Darwin"
