---
- name: Clone dictionaries
  ansible.builtin.git:
    repo: "{{ macos_dictionaries_repo }}"
    dest: "{{ macos_dictionaries_checkout_dir }}"
    version: "{{ macos_dictionaries_repo_version }}"
    update: false
- name: Copy dictionaries
  ansible.builtin.copy:
    remote_src: true
    src: "{{ macos_dictionaries_checkout_dir }}/{{ item }}"
    dest: "{{ macos_dictionaries_install_dir }}/"
    mode: "0644"
  loop: "{{ macos_dictionaries_items }}"
