---
all:
  children:
    workstations:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ lookup('pipe', 'command -v python3') }}"
    servers:
      hosts:
        home_server: {}
