---
- name: Find npm
  ansible.builtin.command:
    cmd: asdf which npm
  register: npm_location
  changed_when: no
- name: Install global packages
  community.general.npm:
    name: "{{ npm_plugins }}"
    global: yes
    state: present
    executable: "{{ npm_location.stdout }}"
- name: Check default npm packages
  ansible.builtin.lineinfile:
    path: "{{ config_dir }}/asdf/default-npm-packages"
    line: "{{ item }}"
    state: present
    create: yes
  loop: "{{ npm_plugins }}"
