---
- name: Install global packages
  community.general.npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop: "{{ npm_plugins }}"
- name: Check default npm packages
  ansible.builtin.lineinfile:
    path: "{{ config_dir }}/asdf/default-npm-packages"
    line: "{{ item }}"
    state: present
    create: yes
  loop: "{{ npm_plugins }}"
