---
- name: Install Alfred
  community.general.homebrew_cask:
    name: "{{ alfred_cask }}"
    state: present
- name: Setup Alfred repo
  ansible.builtin.git:
    repo: git@github.com:TSFoster/alfred.git
    dest: "{{ alfred_dir }}"
    version: 0d1b829f7a6feb3a1e4bef2f42cda08c4eb8a98b
    update: false
- name: Set config dir
  community.general.osx_defaults:
    domain: com.runningwithcrayons.Alfred-Preferences
    key: syncfolder
    value: "{{ alfred_dir }}/"
- name: Install Alfred npm packages
  ansible.builtin.include_role:
    name: common
    tasks_from: install_npm_packages
  vars:
    common_packages: "{{ alfred_npm_packages }}"
    common_package_environment: "{{ asdf_runtime_environment }}"
