---
hammerspoon_cask: hammerspoon
hammerspoon_config_dir: "{{ config_dir }}/hammerspoon"
hammerspoon_downloads_path: "{{ ansible_facts['env']['HOME'] }}/Downloads"
hammerspoon_mailbox_count_binary: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mailbox-count"
hammerspoon_app_launchers:
  - { k: ",", app: System Settings }
  - { k: "0", app: Numbers Creator Studio }
  - { k: "1", app: 1Password }
  - { k: ";", app: Timing }
  - { k: "A", app: Activity Monitor }
  - { k: "a", app: Affinity }
  - { k: "C", app: BusyCal }
  - { k: "d", app: Dash }
  - { k: "e", app: Mail }
  - { k: "f", app: Finder }
  - { k: "F", app: Firefox }
  - { k: "g", app: Google Chrome }
  - { k: "h", app: Home }
  - { k: "i", app: Messages }
  - { k: "I", app: Photos } # Mnemonic: iPhoto
  - { k: "k", app: Keynote Creator Studio }
  - { k: "l", app: Preview } # Mnemonic: Loupe
  - { k: "M", app: Maps }
  - { k: "m", app: Music }
  - { k: "n", app: Drafts }
  - { k: "p", app: Pages Creator Studio }
  - { k: "r", app: Reminders }
  - { k: "R", app: Reeder }
  - { k: "s", app: Ghostty } # Mnemonic: Shell
  - { k: "t", app: Things3 }
  - { k: "u", app: App Store } # Mnemonic: Updates
  - { k: "v", app: Play } # Mnemonic: Videos
  - { k: "w", app: Safari } # Mnemonic: Web
  - { k: "W", app: WhatsApp }
  - { k: "y", app: Notes } # Mnemonic: Yellow notes
  - k: space
    app: /Applications/Alfred 5.app/Contents/Preferences/Alfred Preferences.app
