---
- name: Create ~/.local directory structure
  ansible.builtin.file:
    state: directory
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/{{ item }}"
    mode: "0755"
  loop:
    - bin
    - cache
    - lib
    - share
    - state
- name: Add bin files
  ansible.builtin.copy:
    src: mailbox-count
    dest: "~/.local/bin/"
    mode: preserve
  when: ansible_facts["system"] == "Darwin"
- name: Add ghostty config
  ansible.builtin.template:
    src: ghostty.toml.j2
    dest: "{{ config_dir }}/ghostty/config"
    mode: preserve
- name: Add gh config
  ansible.builtin.copy:
    src: gh
    dest: "{{ config_dir }}/"
    mode: preserve
- name: Add ripgrep config
  ansible.builtin.copy:
    src: ripgreprc
    dest: "{{ config_dir }}/"
    mode: preserve
- name: Add yazi config
  ansible.builtin.copy:
    src: yazi
    dest: "{{ config_dir }}/"
    mode: preserve
- name: Add bat themes
  block:
    - name: Ensure bat config directory exists
      ansible.builtin.file:
        state: directory
        dest: "{{ config_dir }}/bat"
        mode: "0755"
    - name: Download Catppuccin bat themes
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/catppuccin/bat/main/themes/{{ item | urlencode }}"
        dest: "{{ config_dir }}/bat/{{ item }}"
        mode: "0644"
        force: false
      loop:
        - Catppuccin Latte.tmTheme
        - Catppuccin Frappe.tmTheme
        - Catppuccin Macchiato.tmTheme
        - Catppuccin Mocha.tmTheme
- name: Add git config
  block:
    - name: Copy config
      ansible.builtin.copy:
        src: git
        dest: "{{ config_dir }}/"
        mode: preserve
    - name: Add git credentials
      ansible.builtin.template:
        src: credentials.gitconfig.j2
        dest: "{{ config_dir }}/git/credentials.gitconfig"
        mode: "0600"
- name: Add editorconfig
  ansible.builtin.copy:
    src: editorconfig
    dest: ~/.editorconfig
    mode: preserve
- name: Add warpd config
  ansible.builtin.copy:
    src: warpd
    dest: "{{ config_dir }}/warpd/config"
    mode: preserve
