---
- name: Configure Dock
  block:
    - name: Group windows by application
      community.general.osx_defaults:
        domain: com.apple.dock
        key: expose-group-apps
        type: bool
        value: yes
        state: present
    - name: Remove persistent apps
      community.general.osx_defaults:
        domain: com.apple.dock
        key: persistent-apps
        type: array
        value: []
        state: present
    - name: Don’t show indicators for open applications
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-process-indicators
        type: bool
        value: no
        state: present
    - name: Don’t show recent apps in Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: no
        state: present
    - name: Auto-hide dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: yes
        state: present
- name: Configure Safari
  block:
    - name: Restore session at launch
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: AlwaysRestoreSessionAtLaunch
        type: bool
        value: yes
        state: present
    - name: Don’t open safe downloads
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: AutoOpenSafeDownloads
        type: bool
        value: no
        state: present
    - name: Set search engine to DuckDuckGo
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: SearchProviderShortName
        type: string
        value: DuckDuckGo
        state: present
    - name: Don’t use background image
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: ShowBackgroundImageInFavorites
        type: bool
        value: no
        state: present
    - name: Show full URL
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: ShowFullURLInSmartSearchField
        type: bool
        value: yes
        state: present
    - name: Always open tabs
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: TabCreationPolicy
        type: int
        value: 2
        state: present
- name: Configure iTerm2
  block:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: "{{ config_dir }}/iterm2"
        state: directory
    - name: Set Prefs location
      community.general.osx_defaults:
        domain: com.googlecode.iterm2
        key: PrefsCustomFolder
        value: "{{ config_dir }}/iterm2"
  tags:
    - iterm2
- name: Link airport in /usr/local/bin
  ansible.builtin.file:
    src: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport
    dest: /usr/local/bin/airport
    state: link
  become: yes
- name: Disable window animations
  community.general.osx_defaults:
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: no
    state: present
- name: Disable window animations
  community.general.osx_defaults:
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: no
    state: present
