---
- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages | map(attribute='name') | list }}"
    state: present
- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew_casks }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
    sudo_password: "{{ ansible_become_password }}"
  when: ansible_facts["system"] == "Darwin"
- name: Install mas
  community.general.homebrew:
    name: mas
    state: present
  when: ansible_facts["system"] == "Darwin"
  tags:
    - mas
- name: Install MAS apps
  when: ansible_facts["system"] == "Darwin"
  tags:
    - mas
  block:
    - name: Try to install apps
      community.general.mas:
        id: "{{ item }}"
        state: present
      loop: "{{ mas_apps }}"
  rescue:
    - name: Skip installing apps from MAS
      ansible.builtin.debug:
        msg: "Skipping installing Mac App Store apps. Sign in to the App Store and try again"
