---
- name: Install Java packages
  ansible.builtin.include_role:
    name: common
    tasks_from: install_packages
  vars:
    common_packages: "{{ java_packages }}"
- name: Symlink JDK
  ansible.builtin.file:
    src: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
    dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
    state: link
  become: true
  when: ansible_facts["system"] == "Darwin"
- name: Check svn extension exists
  ansible.builtin.stat:
    path: /opt/homebrew/lib/libsvnjavahl-1.dylib
  register: java_svn_extension
  when: ansible_facts["system"] == "Darwin"
- name: Symlink svn extension
  ansible.builtin.file:
    src: /opt/homebrew/lib/libsvnjavahl-1.dylib
    dest: /Library/Java/Extensions/libsvnjavahl-1.dylib
  when: ansible_facts["system"] == "Darwin" and java_svn_extension.stat.exists
