---
- name: Install fish
  community.general.homebrew:
    name: fish
    state: present
- name: Add fish to available shells
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ homebrew_brew_bin_path }}/fish"
    state: present
- name: Change user shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ the_user }}"
    shell: "{{ homebrew_brew_bin_path }}/fish"
- name: Add .hushlogin
  ansible.builtin.file:
    path: "~/.hushlogin"
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: "0644"
- name: Add zprofile
  ansible.builtin.template:
    src: zprofile.j2
    dest: ~/.zprofile
    mode: "0644"
- name: Add bash_profile
  ansible.builtin.template:
    src: bash_profile.j2
    dest: ~/.bash_profile
    mode: "0644"
- name: Create fish_variables
  ansible.builtin.file:
    path: "{{ config_dir }}/fish/fish_variables"
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: "0644"
  tags:
    - vars_debug
- name: Set fish universal shell variables
  ansible.builtin.lineinfile:
    path: "{{ config_dir }}/fish/fish_variables"
    create: true
    mode: "0644"
    regexp: "^SETUVAR (--export )?(--path )?{{ item.name }}:"
    line: >-
      SETUVAR{{ ' ' }}
      {% if item.export | default(false, true) %}--export {% endif -%}
      {% if item.path | default(false, true) %}--path {% endif -%}
      {{ item.name }}:
      {{- item.value_multiple | default([item.value])
        | join('\x1e')
        | replace(' ', '\x20')
        | replace('%', '\x25')
        | replace('(', '\x28')
        | replace(')', '\x29')
        | replace('-', '\x2d')
        | replace('.', '\x2e')
        | replace('<', '\x3c')
        | replace('=', '\x3d')
        | replace('>', '\x3e')
        | replace('{', '\x7b')
        | replace('}', '\x7d')
        | replace('~', '\x7e')
      }}
  loop: "{{ shells_variables + shells_fish_universal_variables }}"
  tags:
    - vars_debug
- name: Set fish abbreviations
  ansible.builtin.lineinfile:
    path: "{{ config_dir }}/fish/fish_variables"
    create: true
    mode: "0644"
    regexp: "^SETUVAR _fish_abbr_{{ item.name }}:"
    line: >-
      SETUVAR _fish_abbr_{{ item.name }}:
      {{- [item.value]
        | join('\x1e')
        | replace(' ', '\x20')
        | replace('%', '\x25')
        | replace('(', '\x28')
        | replace(')', '\x29')
        | replace('-', '\x2d')
        | replace('.', '\x2e')
        | replace('<', '\x3c')
        | replace('=', '\x3d')
        | replace('>', '\x3e')
        | replace('{', '\x7b')
        | replace('}', '\x7d')
        | replace('~', '\x7e')
      }}
  loop: "{{ shells_abbreviations }}"
  tags:
    - vars_debug
- name: Copy fish config
  block:
    - name: Copy dirs
      ansible.builtin.copy:
        src: "{{ item }}/"
        dest: "{{ config_dir }}/fish/{{ item }}/"
        mode: preserve
      loop:
        - bin
        - functions
        - completions
    - name: Make config.fish
      ansible.builtin.template:
        src: "config.fish.j2"
        dest: "{{ config_dir }}/fish/config.fish"
        mode: "0644"
- name: Make conf.d dir
  ansible.builtin.file:
    path: "{{ config_dir }}/fish/conf.d"
    state: directory
    mode: "0755"
- name: Make themes dir
  ansible.builtin.file:
    path: "{{ config_dir }}/fish/themes"
    state: directory
    mode: "0755"
- name: Get homebrew config
  ansible.builtin.command:
    creates: "{{ config_dir }}/fish/conf.d/_0homebrew.fish"
    cmd: "{{ homebrew_brew_bin_path }}/fish -c '{{ homebrew_brew_bin_path }}/brew shellenv fish > {{ config_dir }}/fish/conf.d/_0homebrew.fish'"
- name: Check fisher installed
  ansible.builtin.command:
    cmd: 'fish -c "functions -q fisher; and echo installed; exit 0"'
  register: shells_which_fisher
  changed_when: false
  tags:
    - fisher
- name: Install fisher
  ansible.builtin.command:
    cmd: "fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'"
  changed_when: true
  when: shells_which_fisher.stdout.find('installed') == -1
  tags:
    - fisher
- name: Get list of plugins
  ansible.builtin.command:
    cmd: "fish -c 'fisher list'"
  register: shells_fisher_list
  changed_when: false
  tags:
    - fisher
- name: Install fisher plugins
  ansible.builtin.command:
    cmd: "fish -c 'fisher install {{ item }}'"
  changed_when: true
  when: shells_fisher_list.stdout.find(item) == -1
  loop: "{{ shells_fisher_plugins }}"
  tags:
    - fisher
- name: Install thefuck
  community.general.homebrew:
    name: thefuck
    state: present
- name: Install thefuck for fish
  ansible.builtin.command:
    creates: "{{ config_dir }}/fish/functions/fuck.fish"
    cmd: fish -c 'thefuck --alias > {{ config_dir }}/fish/functions/fuck.fish'
- name: Install atuin
  community.general.homebrew:
    name: atuin
    state: present
- name: Add atuin config
  ansible.builtin.copy:
    src: "atuin"
    dest: "{{ config_dir }}/atuin/"
    mode: preserve
