---
ansible_host: "{{ vault_ansible_host }}"
ansible_become_password: "{{ vault_ansible_become_password }}"

wake_on_lan_mac_address: "{{ vault_wake_on_lan_mac }}"

base_data: /srv/data
base_data_device: /dev/disk/media

tailscale_authkey: "{{ vault_tailscale_authkey }}"
tailscale_advertise_routes:
  - 192.168.68.0/24
tailscale_advertise_connector: true
tailscale_advertise_exit_node: true

ts_oauth_client_id: kzCzRStE2b11CNTRL
ts_oauth_client_secret: "{{ vault_ts_oauth_client_secret }}"

unattended_upgrades_healthcheck_url: "{{ vault_unattended_upgrades_healthcheck_url }}"
