---
nvim_lsp_npm_packages:
  - "@ansible/ansible-language-server"
  - "@fsouza/prettierd"
  - bash-language-server
  - dockerfile-language-server-nodejs
  - "@olrtg/emmet-language-server"
  - prettier
  - pyright
  - "@tailwindcss/language-server"
  - tree-sitter-cli
  - typescript-language-server
  - vscode-langservers-extracted
  - yaml-language-server

nvim_lsp_homebrew_packages_darwin:
  - deno
  - gopls
  - lua-language-server
  - marksman
  - rust-analyzer
  - stylua

nvim_lsp_gem_packages:
  - solargraph
