---
- name: Install machine-share
  community.general.npm:
    name: machine-share
    global: yes
    state: present
- name: Install hostile
  community.general.npm:
    name: hostile
    global: yes
    state: present
