---
- name: Load Neovim vim.pack state
  ansible.builtin.include_tasks: _load_pack_state.yml

- name: Capture sorted Neovim vim.pack plugin names
  ansible.builtin.set_fact:
    nvim_pack_list_plugin_names: >-
      {{ nvim_pack_lockfile_plugin_names | sort }}
  changed_when: false

- name: Print Neovim vim.pack plugin names
  ansible.builtin.debug:
    msg: "{{ nvim_pack_list_plugin_names }}"
  changed_when: false
