---
- name: Install python neovim module
  ansible.builtin.include_role:
    name: common
    tasks_from: install_pip_packages
  vars:
    common_packages: "{{ nvim_python_module_packages }}"
- name: Install ruby neovim module
  ansible.builtin.include_role:
    name: common
    tasks_from: install_gem_packages
  vars:
    common_packages:
      - neovim
    common_package_environment: "{{ nvim_ruby_environment }}"
  when: ansible_facts['system'] == 'Darwin'
- name: Install Neovim LSP tool packages
  ansible.builtin.include_role:
    name: common
    tasks_from: install_packages
  vars:
    common_packages: "{{ nvim_packages }}"

- name: Install Neovim npm packages
  ansible.builtin.include_role:
    name: common
    tasks_from: install_npm_packages
  vars:
    common_packages: "{{ nvim_npm_packages }}"
    common_package_environment: "{{ nvim_npm_environment }}"
  tags:
    - nvim_lsp

- name: Install Neovim Ruby gem packages
  ansible.builtin.include_role:
    name: common
    tasks_from: install_gem_packages
  vars:
    common_packages: "{{ nvim_gem_packages }}"
  tags:
    - nvim_lsp

- name: Copy files
  ansible.builtin.copy:
    src: ./
    dest: "{{ nvim_config_dir }}/"
    mode: preserve
  tags:
    - nvim_files

- name: Add nvr completion in fish
  block:
    - name: Ensure fish completions directory exists
      ansible.builtin.file:
        path: "{{ nvim_fish_completions_dir }}"
        state: directory
        mode: "0755"
    - name: Download nvr fish completion
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/mhinz/neovim-remote/master/contrib/completion.fish
        dest: "{{ nvim_fish_completion_path }}"
        mode: "0644"
        force: false
