---
- name: Install nvim package
  vars:
    package_pack: "{{ item.pack | default('main') }}"
    package_when: "{{ item.start | default(true) | ternary('start', 'opt') }}"
    package_name: "{{ item.name | default (item.url | basename) }}"
    package_dest: "{{ config_dir }}/nvim/pack/{{ package_pack }}/{{ package_when }}/{{ package_name }}"
  block:
    - name: Clone repo
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: "{{ package_dest }}"
        update: "{{ update_nvim_packages | default(false) }}"
      register: clone_status
    - name: Execute do command
      ansible.builtin.shell:
        cmd: "{{ item.do }}"
        chdir: "{{ package_dest }}"
      when: "item.do is defined and clone_status.before != clone_status.after"
