---
- name: Get list of fonts available to install via iCloud Drive # TODO Separate out fonts that I actaully want installed
  ansible.builtin.find:
    paths: "{{ ansible_facts['env']['HOME'] }}/Library/Mobile Documents/com~apple~CloudDocs/Data/Fonts/"
    recurse: true
    patterns: "*.otf"
  register: fonts_icloud_fonts
- name: Install fonts
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item }}"
    dest: "~/Library/Fonts/"
    mode: "0644"
  loop: "{{ fonts_icloud_fonts.files | map(attribute='path') }}"
